{% set name = "BubbleDet" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bubbledet-{{ version }}.tar.gz
  sha256: 5175ed2b0d363e62243cfdd5f88517d93bcdaa9e376abcc2118cf358c8695f20

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - cosmotransitions >=2.0.6
    - findiff >=0.9.2
    - numpy >=1.21.5
    - packaging >=21.3
    - scipy >=1.8.0

test:
  imports:
    - BubbleDet
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  license: MIT
  license_file: LICENSE
  home: https://bubbledet.readthedocs.io/
  dev_url: https://bitbucket.org/og113/bubbledet/
  summary: 'A package for computing functional determinants'
  description: |
    BubbleDet is a Python package for computing functional determinants which
    arise in the bubble nucleation rate, whether in the context of early
    universe cosmology or table-top physics experiments.

extra:
  recipe-maintainers:
    - og113
    - AndreasEkstedt
    - joonashir
